export const Questions = [
  {
    prompt: "Which of these describe your current role?",
    optionA: "Student",
    optionB: "Employed",
    optionC: "Self-Employed",
    optionD: "Other",
    answer: "optionD",
  },
  {
    prompt: "How did you hear about us?",
    optionA: "TV Ads",
    optionB: "Social Media",
    optionC: "Friends",
    optionD: "Newspaper",
    answer: "optionC",
  },
  {
    prompt: "Aspiration?",
    optionA: "Front-end Developer",
    optionB: "Back-end Developer",
    optionC: "Andriod App Developer",
    optionD: "I don't know yet",
    answer: "optionA",
  },
  {
    prompt: "Who is the Nigerian President?",
    optionA: "Buhari",
    optionB: "Osinbajo",
    optionC: "Obi",
    optionD: "Tinubu",
    answer: "optionD",
  },
  {
    prompt: "Did you do well?",
    optionA: "Maybe",
    optionB: "Definitely",
    optionC: "I don't think so",
    optionD: "Up to you",
    answer: "optionD",
  },
];
